### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by kevahere** [andyrichardson/atom-updater-linux#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-updater-linux](https://github.com/andyrichardson/atom-updater-linux) package 1.2.2

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/packages/atom-updater-linux/src/lib/updater.js:111:37)
    at Request.self.callback (/packages/atom-updater-linux/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /packages/atom-updater-linux/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /packages/atom-updater-linux/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
 33x -6:28.6.0 core:move-down (input.hidden-input)
     -6:02.1.0 intentions:highlight (input.hidden-input)
     -6:01.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-typescript 11.0.6 
atom-updater-linux 1.2.2 
build 0.70.0 
build-python 0.9.3 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.7 
gpp-compiler 3.0.7 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.2.4 
minimap 4.29.8 
platformio-ide-terminal 2.8.3 
```

**Comment by andyrichardson** [comment]
Hey @kevahere, thanks for the report.

The issue is likely due to one of two issues:
 * Bad network conditions (invalid proxy config, network timeout etc.)
 * Exceeding the Atom API limit

I'll leave the issue open for now but if you can test on a different network, you should find everything to be working fine.
