### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.16.5.1:8080

### ISSUE THREAD

**Issue by masiddique** [andyrichardson/atom-updater-linux#25]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: [atom-updater-linux](https://github.com/andyrichardson/atom-updater-linux) package 1.3.0

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.16.5.1:8080

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.16.5.1:8080
    at ClientRequest.onError (/packages/atom-updater-linux/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-updater-linux 1.3.0 
file-icons 2.1.34 
highlight-selected 0.16.0 
ide-r 0.1.8 
indent-detective 0.4.0 
ink 0.10.12 
julia-client 0.9.4 
language-julia 0.19.1 
language-markdown 0.37.0 
latex-completions 0.3.6 
markdown-preview-plus 3.9.3 
pandoc 0.2.2 
tool-bar 1.1.12 
uber-juno 0.2.0 
xml-formatter 0.13.0 
```

**Comment by andyrichardson** [comment]
Thanks for the report - closing this in favor of #24 which looks to be the same issue.
